/* KBO fan playtest: take charge of 한화 이글스 through the real UI flow, inspect lineup/rotation/bullpen/2군, theme, salaries */
(async () => {
  const L = []; const note = t => { PT.note(t); L.push(t) };
  PT.say("타이틀 → 새로 시작 → 한화");
  PT.click("#btnNew"); await PT.until(() => PT.visible("#screen-team"));
  const cards = document.querySelectorAll("#teamCards .tc");
  note("team cards " + cards.length + " : " + [...cards].map(c => c.textContent.trim().replace(/\s+/g, " ").slice(0, 60)).join(" | "));
  const idx = APP.teamList().findIndex(t => t.code === "HH");
  cards[idx].click(); note("teamPick text: " + PT.text("#teamPick"));
  await PT.click("#teamStart");
  await PT.until(() => PT.visible("#eventModal"), 5000);
  note("event: " + PT.text("#eventTitle") + " / " + PT.text("#eventBody"));
  PT.click("#eventOk");
  await PT.until(() => PT.visible("#tutorial"), 3000); note("tutorial text: " + PT.text("#tutText")); PT.click("#tutSkip");
  const S = ClubUI.state(); const P = id => S.players.find(p => p.id === id);
  const cs = getComputedStyle(document.documentElement);
  note("club " + S.club.name + " color " + S.club.color + "/" + S.club.color2 + " css --team " + cs.getPropertyValue("--team").trim() + " --bulb " + cs.getPropertyValue("--bulb").trim() + " --go " + cs.getPropertyValue("--go").trim());
  const fmtP = p => p.name + "#" + p.num + " " + (p.pos || p.role) + " " + (p.bats || "") + "/" + (p.throws || "") + " " + p.age + "세 " + p.contract.salary + "억 ovr" + ClubInt.ovr(p).toFixed(2) + (p.real ? "" : "(est)");
  note("LINEUP: " + S.lineup.map((id, i) => (i + 1) + "." + fmtP(P(id))).join(" | "));
  note("ROTATION: " + S.rotation.map((id, i) => (i + 1) + "." + fmtP(P(id))).join(" | "));
  const act = S.players.filter(p => p.active);
  note("1군 " + act.length + " (타자 " + act.filter(p => p.type == "B").length + " 투수 " + act.filter(p => p.type == "P").length + ") 2군 " + S.players.filter(p => !p.active).length + " 전체 " + S.players.length);
  note("BULLPEN: " + act.filter(p => p.type == "P" && !S.rotation.includes(p.id)).map(fmtP).join(" | "));
  note("BENCH: " + act.filter(p => p.type == "B" && !S.lineup.includes(p.id)).map(fmtP).join(" | "));
  note("TOP SALARY: " + S.players.slice().sort((a, b) => b.contract.salary - a.contract.salary).slice(0, 12).map(p => p.name + " " + p.contract.salary + "억(" + p.age + "세 " + (p.pos || p.role) + ")" + (p.active ? "" : "[2군]")).join(", "));
  note("top40 " + ClubInt.top40().toFixed(1) + " budget " + S.budget + " contracts status sample: " + act.slice(0, 8).map(p => p.name + ":" + p.contract.status + "/" + p.contract.years + "y").join(", "));
  const known = ["류현진", "문동주", "노시환", "채은성", "엄상백", "이재원", "폰세", "와이스", "심우준", "강백호", "김서현", "주현상", "하주석", "최재훈", "황영묵", "정은원", "김태연", "문현빈", "페라자", "짐머맨", "화이트", "왕옌청", "안치홍", "이진영", "장민재", "한승혁"];
  note("KNOWN: " + known.map(n => { const p = S.players.find(x => x.name === n); return n + "=" + (p ? (p.active ? "1군" : "2군") + " " + (p.pos || p.role) + " " + p.age + "세 " + p.hand + " " + p.contract.salary + "억" + (p.real ? "" : " est") : "없음") }).join(" | "));
  const cnt = {}; S.players.forEach(p => cnt[p.name] = (cnt[p.name] || 0) + 1);
  note("DUP NAMES: " + Object.entries(cnt).filter(([n, c]) => c > 1).map(([n, c]) => n + "x" + c + " " + S.players.filter(p => p.name === n).map(p => "#" + p.num + " " + p.age + "세" + p.hand + (p.active ? "1군" : "2군")).join("/")).join(", "));
  const est = S.players.filter(p => !p.real);
  note("EST players " + est.length + " age min/max " + Math.min(...est.map(p => p.age)) + "/" + Math.max(...est.map(p => p.age)) + " · est 1군 " + est.filter(p => p.active).length);
  note("POS COUNT 1군 타자: " + JSON.stringify(act.filter(p => p.type == "B").reduce((a, p) => (a[p.pos] = (a[p.pos] || 0) + 1, a), {})) + " 투수 role: " + JSON.stringify(act.filter(p => p.type == "P").reduce((a, p) => (a[p.role] = (a[p.role] || 0) + 1, a), {})));
  note("LEFTY in lineup: " + S.lineup.map(P).filter(p => p.hand === "L").length + "/9 · switch hitters shown as: " + S.players.filter(p => p.bats === "S").map(p => p.name + "→" + p.hand).join(","));
  APP.show("roster"); await PT.wait(400);
  note("roster screen lineup warn: " + (document.querySelector("#lineup .warn") ? document.querySelector("#lineup .warn").textContent : "none") + " | rosterList head: " + (document.querySelector("#rosterList th") || {}).textContent);
  note("rotation panel: " + (document.getElementById("rotation").innerText || "").replace(/\s+/g, " ").slice(0, 400));
  note("strip: " + ["tDate", "tRec", "tRank", "tBudget", "tPay", "tMorale"].map(id => id + "=" + PT.text("#" + id)).join(" "));
  note("FA panel rows: " + document.querySelectorAll("#market tr").length + " text " + (document.getElementById("market").innerText || "").replace(/\s+/g, " ").slice(0, 300));
  await PT.done({ persona: "KBO 골수팬 · 한화 이글스 부임", notes: L });
})();
