/* sim_v2_lineup: re-verify lineup stacking on the patched build
   (c) empty-slot lineups raise 타선 strength (quick sim)  (c-UI) reachable via 2군 내리기  (d) position relabel kills the defense penalty
   (d4) best-26-from-whole-org  (a) pitcher in lineup: quick sim + physics game (hang?)  (b) 9x same hitter: quick sim + game screen  (e) 8-man lineup start guard
   (f) injured starter left in lineup  (g) draw recording: 1-inning 0:0 physics game → header/log/schedule */
(async () => {
  const I = ClubInt, r2 = v => Math.round(v * 100) / 100, avg = a => a.length ? a.reduce((x, y) => x + y, 0) / a.length : 0;
  const fresh = i => { ClubUI.fresh(APP.teamList()[i === undefined ? 4 : i]); return ClubUI.state() };
  const strengths = () => { ClubUI.render(); const t = PT.text("#nextGame") || ""; const m = t.match(/타선 ([\d.]+) · 수비 ([\d.]+)/); return m ? { B: +m[1], D: +m[2] } : null };
  const season = () => { const S = ClubUI.state(); let d = 0; while (S.sched.filter(g => g.result).length < 30 && d++ < 60) ClubUI.simDay(); return { W: S.W, L: S.L, runs: S.runs, ra: S.ra } };
  const batScore = p => 0.4 * p.attrs.contact + 0.3 * p.attrs.power + 0.3 * p.attrs.eye;
  const bats = () => ClubUI.state().players.filter(p => p.type == "B" && p.active).sort((a, b) => batScore(b) - batScore(a));
  const fastWithGuard = async ms => { let stopped = false; const t = setTimeout(() => { stopped = true; PT.click("#stop") }, ms); await GameUI.fast(); clearTimeout(t); return stopped };
  const clickAct = async (act, pid) => { for (let pg = 0; pg < 40; pg++) { const btn = document.querySelector("[data-act=" + act + "][data-pid='" + pid + "']"); if (btn) { btn.click(); await PT.wait(10); return true } const nb = document.querySelector("#rosterList [data-pg][data-d='1']"); if (!nb) return false; nb.click(); await PT.wait(10) } return false };
  const need = ["C", "1B", "2B", "3B", "SS", "LF", "CF", "RF", "DH"];
  const out = {};
  try {
    let S = fresh(); const ctrl = { ...strengths(), ...season() }; PT.note("control: " + JSON.stringify(ctrl)); out.ctrl = ctrl;
    for (const N of [5, 3, 1]) { S = fresh(); const b = bats(); S.lineup = b.slice(0, N).map(p => p.id).concat(Array(9 - N).fill(null)); I.save(); const st = strengths(); const r = season(); out["top" + N] = { ...st, ...r }; PT.note("(c) top-" + N + " + " + (9 - N) + " empty: " + JSON.stringify(out["top" + N]) + " warn: " + ((document.querySelector("#lineup .warn") || {}).textContent || "none")) }
    // (c-UI) reach empty slots through the roster screen
    S = fresh(); APP.show("roster"); await PT.wait(50); const bench = S.players.filter(p => p.type == "B" && p.active && !S.lineup.includes(p.id)); for (const p of bench) await clickAct("down", p.id);
    const worst = S.lineup.map(I.P).filter(Boolean).sort((a, b) => batScore(a) - batScore(b)).slice(0, 4); let nd = 0; for (const p of worst) if (await clickAct("down", p.id)) nd++;
    PT.note("(c-UI) demoted bench " + bench.length + " + worst starters " + nd + ": lineup " + S.lineup.map(id => { const p = I.P(id); return p ? p.name : "null" }).join("/") + " active " + S.players.filter(p => p.active).length + " · " + JSON.stringify(strengths()) + " · lineup table text: " + ((document.querySelector("#lineup") || {}).textContent || "").replace(/\s+/g, " ").slice(0, 100));
    const rUI = season(); PT.note("(c-UI) season with " + S.lineup.filter(id => I.P(id)).length + "-man lineup via UI: " + JSON.stringify(rUI) + " errs " + PT.errs.length); out.ui = rUI;
    // (d) position relabel
    S = fresh(); const w0 = I.positionWarnings(); const st0 = strengths(); S.lineup.map(I.P).forEach((p, i) => { if (p) p.pos = need[i] }); I.save(); const st1 = strengths();
    PT.note("(d) relabel: warnings " + JSON.stringify(w0) + " D " + st0.D + " -> " + JSON.stringify(I.positionWarnings()) + " D " + st1.D + " · posSel in UI editable=" + !!document.querySelector(".posSel"));
    S = fresh(); let b = bats(); S.lineup = b.slice(0, 5).map(p => p.id).concat(Array(4).fill(null)); S.lineup.map(I.P).filter(Boolean).forEach((p, i) => p.pos = need[i]); I.save(); const st3 = strengths(); const r3 = season(); PT.note("(d3) top-5 relabeled + 4 empty: " + JSON.stringify({ ...st3, ...r3 }));
    // (d4) best 26 from whole org
    S = fresh(); { const all = S.players; const bb = all.filter(p => p.type == "B").sort((a, b) => I.ovr(b) - I.ovr(a)); const pp = all.filter(p => p.type == "P").sort((a, b) => I.ovr(b) - I.ovr(a)); const gems = bb.slice(0, 13).filter(p => !p.active).length + pp.slice(0, 13).filter(p => !p.active).length;
      all.forEach(p => p.active = false); bb.slice(0, 13).forEach(p => p.active = true); pp.slice(0, 13).forEach(p => p.active = true); pp.slice(0, 5).forEach(p => p.role = "SP"); pp.slice(5, 13).forEach(p => p.role = "RP"); S.lineup = bb.slice(0, 9).map(p => p.id); S.rotation = pp.slice(0, 5).map(p => p.id); I.save();
      const st4 = strengths(); const r4 = season(); PT.note("(d4) best-26-from-org (" + gems + " from 2군): lineup ovr " + r2(avg(S.lineup.map(id => I.ovr(I.P(id))))) + " rot ovr " + r2(avg(S.rotation.map(id => I.ovr(I.P(id))))) + " " + JSON.stringify({ ...st4, ...r4 }) + " vs control " + JSON.stringify(ctrl)) }
    // (a) pitcher in lineup
    S = fresh(); const sp = I.P(S.rotation[0]); S.lineup[0] = sp.id; I.save(); const stP = strengths(); ClubUI.simDay(); const g1 = S.sched.find(g => g.result);
    PT.note("(a) pitcher " + sp.name + " in slot 1: strengths " + JSON.stringify(stP) + " · quick-sim result " + JSON.stringify(g1 && g1.result) + " · his bat stats G/PA " + sp.stats.G + "/" + sp.stats.PA + " · errs " + PT.errs.length);
    APP.show("game"); await PT.wait(150); const CL = APP.clubLineup; const selNames = [...document.querySelectorAll("[data-b].sel")].map(e => e.querySelector("b").textContent.replace(/\s+/g, " "));
    PT.note("(a2) game screen: clubLineup.order=" + JSON.stringify(CL && CL.order) + " pick.order=" + JSON.stringify(GameUI.pick.order) + " selected=" + selNames.length + " [" + selNames.join("/").slice(0, 120) + "] start disabled=" + document.getElementById("start").disabled);
    document.getElementById("innings").value = 1; document.getElementById("seed").value = 3;
    if (!document.getElementById("start").disabled) { await document.getElementById("start").onclick(); const started = await PT.until(() => !document.getElementById("game").hidden, 3000).then(() => true).catch(() => false); const feedTxt = (PT.text("#feed") || "").slice(-80);
      if (started && !document.getElementById("game").hidden) { const stopped = await fastWithGuard(6000); const G = GameUI.state(); PT.note("(a3) 1-inning game: stopped=" + stopped + " over=" + (G && G.over) + " pitches " + (G ? G.pitches.us + G.pitches.them : "-") + " · errs " + JSON.stringify(PT.errs).slice(0, 200)); await PT.shot("pitcher_in_lineup"); if (G && !G.over) { document.querySelector(".call[data-call='take']").click(); await fastWithGuard(6000); PT.note("(a3b) after sign change: over=" + GameUI.state().over + " pitches " + (GameUI.state().pitches.us + GameUI.state().pitches.them)) } if (GameUI.state() && GameUI.state().over) { PT.click("#resume"); await PT.until(() => PT.visible("#eventModal"), 3000).catch(() => 0); PT.note("(a4) event: " + (PT.text("#eventBody") || "").replace(/\s+/g, " ").slice(0, 80) + " · locked=" + APP.locked); PT.click("#eventOk"); await PT.wait(30) } else PT.note("(a4) game stuck; locked=" + APP.locked) } else PT.note("(a3) start refused: feed=" + feedTxt + " locked=" + APP.locked) }
    // (b) 9x hero
    if (APP.locked) { PT.note("(b) skipped: app locked"); } else {
      S = fresh(); b = bats(); const hero = b[0]; S.lineup = Array(9).fill(hero.id); I.save(); const stD = strengths(); ClubUI.simDay(); const gD = S.sched.find(g => g.result);
      PT.note("(b) 9x " + hero.name + ": strengths " + JSON.stringify(stD) + " warnings " + JSON.stringify(I.positionWarnings()) + " result " + JSON.stringify(gD && gD.result) + " hero G/PA after 1 game " + hero.stats.G + "/" + hero.stats.PA + " · UI lineup rows " + document.querySelectorAll("#lineup tr").length);
      const rDup = season(); PT.note("(b2) 9x hero season: " + JSON.stringify(rDup) + " hero G/PA " + hero.stats.G + "/" + hero.stats.PA + " fatigue " + r2(hero.fatigue)); out.dup = rDup;
      // can the UI produce a duplicate? swap flow: click .swap on slot then click the same player row
      S = fresh(); APP.show("roster"); await PT.wait(50); const sw = document.querySelector(".swap"); if (sw) { sw.click(); await PT.wait(20); const rows = [...document.querySelectorAll("#rosterList .pr")]; const target = rows.find(r => +r.dataset.pid === S.lineup[1]) || rows[1]; if (target) target.click(); await PT.wait(30) } PT.note("(b3) UI swap slot1 with lineup[1] player: lineup " + S.lineup.map(id => (I.P(id) || {}).name).join("/") + " dup=" + (new Set(S.lineup).size !== 9));
      APP.show("game"); await PT.wait(150); PT.note("(b4) game screen for 9x lineup: pick.order=" + JSON.stringify(GameUI.pick.order) + " selected cards=" + document.querySelectorAll("[data-b].sel").length + " start disabled=" + document.getElementById("start").disabled + " order label=" + (PT.text("#orderLabel") || PT.text("#pickInfo") || "-"));
      // (e) 8-man lineup
      S = fresh(); S.lineup[8] = null; I.save(); APP.show("game"); await PT.wait(150); const before = document.querySelectorAll("[data-b].sel").length; PT.note("(e) 8-man lineup: clubLineup.order=" + JSON.stringify(APP.clubLineup && APP.clubLineup.order) + " selected=" + before + " start disabled=" + document.getElementById("start").disabled); if (before < 9) { document.getElementById("innings").value = 1; await document.getElementById("start").onclick(); await PT.wait(100); PT.note("(e2) start with " + before + " selected: game hidden=" + document.getElementById("game").hidden + " feed=" + (PT.text("#feed") || "").replace(/\s+/g, " ").slice(-80)) }
      // (f) injured starter stays in lineup
      S = fresh(); const L = S.lineup.map(I.P); const bad = L.slice().sort((a, b) => batScore(a) - batScore(b))[0]; const stI0 = strengths(); bad.injury = 30; const stI1 = strengths(); ClubUI.simDay();
      PT.note("(f) worst starter " + bad.name + " injured 30d left in lineup: B " + stI0.B + " -> " + stI1.B + " D " + stI0.D + " -> " + stI1.D + " · after a game his G=" + bad.stats.G + " · still in lineup=" + S.lineup.includes(bad.id) + " · UI warns? " + ((document.querySelector("#lineup") || {}).textContent || "").includes("부상"));
      // (g) draws: 1-inning physics game, several seeds until a 0:0 or tie
      S = fresh(); let tie = null; for (let sd = 1; sd <= 6 && !tie; sd++) { let k = 0; while (!S.sched.find(g => g.date === I.today() && !g.result) && k++ < 5) ClubUI.simDay(); APP.show("game"); await PT.wait(80); PT.click("#autoOrder"); const pc = document.querySelector("[data-p='0']"); if (pc) pc.click(); document.getElementById("seed").value = sd; document.getElementById("innings").value = 1; await document.getElementById("start").onclick(); await PT.until(() => !document.getElementById("game").hidden, 3000).catch(() => 0); await fastWithGuard(6000); const G = GameUI.state(); if (!G || !G.over) { document.querySelector(".call[data-call='take']").click(); await fastWithGuard(6000) } const G2 = GameUI.state(); const us = G2.score.us.reduce((a, b) => a + b, 0), th = G2.score.them.reduce((a, b) => a + b, 0); PT.click("#resume"); await PT.until(() => PT.visible("#eventModal"), 3000).catch(() => 0); const ev = (PT.text("#eventBody") || "").replace(/\s+/g, " ").slice(0, 60); PT.click("#eventOk"); await PT.wait(30); const g = S.sched.filter(x => x.result).slice(-1)[0]; PT.note("(g) seed " + sd + " 1-inning: " + us + ":" + th + " ev '" + ev + "' header " + PT.text("#tRec") + " · sched result " + JSON.stringify(g && g.result) + " · log " + S.log[0].t.slice(0, 50)); if (us === th) tie = { us, th, ev, rec: PT.text("#tRec"), log: S.log[0].t }; ClubUI.simDay() }
      if (tie) { APP.show("schedule"); await PT.wait(60); PT.note("(g2) draw: schedule cell text has 무? " + ((document.querySelector("#schedule") || document.body).textContent.includes("무")) + " · rank row: " + (PT.text("#rank") || "").replace(/\s+/g, " ").slice(0, 80)); out.draw = tie } else PT.note("(g) no tie in 6 seeds");
    }
  } catch (e) { PT.note("FATAL " + e.message + " " + (e.stack || "").slice(0, 300)) }
  await PT.done({ scenario: "v2_lineup", out, errs: PT.errs });
})();
